# Generated by Django 4.2.11 on 2024-04-06 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bank", "0003_accountant_client_manager_delete_bankusers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountant",
            name="bank",
        ),
        migrations.RemoveField(
            model_name="client",
            name="bank",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="bank",
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directors",
                        to="bank.bank",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accountant",
            name="bank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accountants",
                to="bank.bank",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="bank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="bank.bank",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manager",
            name="bank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managers",
                to="bank.bank",
            ),
            preserve_default=False,
        ),
    ]
