# Generated by Django 4.2.11 on 2024-04-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_remove_accountant_bank_remove_client_bank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directors",
                to="bank.bank",
            ),
        ),
    ]
