# Generated by Django 4.2.11 on 2024-03-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountant",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accountants",
                to="bank.bank",
                verbose_name="Bank of the accountant",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="bank.bank",
                verbose_name="Bank of the client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="bank.manager",
                verbose_name="Manager of the client",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="accountant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managers",
                to="bank.accountant",
                verbose_name="Accountant of the manager",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager",
                to="bank.bank",
                verbose_name="Bank of the manager",
            ),
        ),
    ]
