# Generated by Django 4.2.11 on 2024-04-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0005_alter_director_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountant",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accountants",
                to="bank.bank",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="bank.bank",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managers",
                to="bank.bank",
            ),
        ),
    ]
