# Generated by Django 4.2.11 on 2024-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("DIRECTOR", "Director"),
                    ("ACCOUNTANT", "Accountant"),
                    ("MANAGER", "Manager"),
                    ("CLIENT", "Client"),
                ],
                default="CLIENT",
                max_length=20,
            ),
        ),
    ]
