# Generated by Django 4.2.11 on 2024-04-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="client",
            name="user",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="accountant",
        ),
        migrations.RemoveField(
            model_name="manager",
            name="user",
        ),
        migrations.DeleteModel(
            name="Accountant",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
